# Generated by Django 5.1.5 on 2026-03-04 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField(blank=True, help_text='Used for cards/links on the commissions landing page.')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Optional: set a parent to group pages (e.g. commissions as a directory).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='idrisfilms_site.page')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('rich_text', 'Rich text'), ('image', 'Image'), ('cta', 'Call to action'), ('embed', 'Embed (YouTube/Vimeo iframe)')], default='rich_text', max_length=20)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True, help_text='Text or HTML depending on block type.')),
                ('image_url', models.URLField(blank=True, help_text='Optional: link to an image (Cloudinary URL etc).')),
                ('button_text', models.CharField(blank=True, max_length=80)),
                ('button_url', models.URLField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='idrisfilms_site.page')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
