# Generated by Django 5.1.5 on 2026-03-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idrisfilms_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='summary',
            field=models.TextField(blank=True, help_text='Optional: short summary for link cards / intro copy.'),
        ),
    ]
