# Generated by Django 5.1.5 on 2026-03-04 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idrisfilms_site', '0002_alter_page_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('embed_url', models.URLField(blank=True, help_text='Use an embed URL like https://www.youtube.com/embed/VIDEO_ID or https://player.vimeo.com/video/ID')),
                ('embed_html', models.TextField(blank=True, help_text='Optional: paste full iframe HTML instead of embed_url.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='idrisfilms_site.page')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
