# Generated by Django 5.1.5 on 2026-03-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idrisfilms_site', '0003_carouselslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslide',
            name='embed_url',
            field=models.URLField(blank=True, help_text="Paste a normal YouTube/Vimeo link OR an embed URL. We'll convert YouTube/Vimeo links automatically."),
        ),
    ]
