# Generated by Django 5.1.5 on 2026-03-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idrisfilms_site', '0004_alter_carouselslide_embed_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['sort_order', 'title']},
        ),
        migrations.AddField(
            model_name='page',
            name='card_image_url',
            field=models.URLField(blank=True, help_text='Optional: image shown on the commissions category card (paste a Cloudinary URL etc).'),
        ),
        migrations.AddField(
            model_name='page',
            name='showreel_caption',
            field=models.CharField(blank=True, help_text='Optional caption under the commissions landing showreel.', max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='showreel_embed_url',
            field=models.URLField(blank=True, help_text='Commissions landing showreel embed URL (e.g. https://www.youtube-nocookie.com/embed/VIDEO_ID).'),
        ),
        migrations.AddField(
            model_name='page',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Ordering for category cards (lower numbers appear first).'),
        ),
    ]
