# Generated by Django 5.1.5 on 2026-03-04 14:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idrisfilms_site', '0005_alter_page_options_page_card_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload an image for IMAGE blocks.', max_length=255, null=True, verbose_name='block_image'),
        ),
        migrations.AddField(
            model_name='page',
            name='card_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload an image for the category card on /commissions/.', max_length=255, null=True, verbose_name='card_image'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional legacy/manual URL (not needed if you upload image).'),
        ),
        migrations.AlterField(
            model_name='page',
            name='card_image_url',
            field=models.URLField(blank=True, help_text='Optional: legacy/manual image URL (not needed if you upload card_image).'),
        ),
    ]
