# Generated by Django 5.2.5 on 2026-03-05 11:19

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idrisfilms_site', '0006_contentblock_image_page_card_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselslide',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='carouselslide',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the image (optional, but recommended).', max_length=200),
        ),
    ]
