# Generated by Django 5.2.5 on 2026-04-26 13:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idrisfilms_site', '0007_carouselslide_image_carouselslide_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='landing_poster',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional fallback poster image for the landing video.', max_length=255, null=True, verbose_name='landing_poster'),
        ),
        migrations.AddField(
            model_name='page',
            name='landing_video',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload the looping splash landing page video. Use an MP4, ideally compressed under 25MB.', max_length=255, null=True, verbose_name='landing_video'),
        ),
    ]
